name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # или windows-latest для Windows окружения

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Укажите версию .NET, которую вы используете

      - name: Restore dependencies
        run: dotnet restore ILazy.sln  # Восстанавливаем зависимости

      - name: Build
        run: dotnet build ILazy.sln --configuration Release  # Сборка решения

      - name: Test
        run: dotnet test ILazy.sln --configuration Release  # Запуск тестов
