name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # или windows-latest для Windows окружения

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Укажите версию .NET, которую вы используете

      - name: Restore dependencies
        run: |
          cd LazyEvaluation  # Перейдите в папку с вашим проектом
          dotnet restore ILazyEvaluation.sln  # Восстанавливаем зависимости

      - name: Build
        run: |
          cd LazyEvaluation  # Перейдите в папку с вашим проектом
          dotnet build ILazyEvaluation.sln --configuration Release  # Сборка решения

      - name: Test
        run: |
          cd LazyEvaluation.Tests  # Перейдите в папку с вашими тестами
          dotnet test ILazyEvaluation.Tests.csproj --configuration Release  # Запуск тестов
