name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Можно использовать 'windows-latest' для Windows окружения

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Укажите версию .NET, которую вы используете

      - name: Restore dependencies
        run: |
          dotnet restore "C:\Users\Aorus\Desktop\ILazy\LazyEvaluation\ILazyEvaluation.sln"

      - name: Build
        run: |
          dotnet build "C:\Users\Aorus\Desktop\ILazy\LazyEvaluation\ILazyEvaluation.sln" --configuration Release

      - name: Test
        run: |
          dotnet test "C:\Users\Aorus\Desktop\ILazy\LazyEvaluation.Tests\ILazyEvaluation.Tests.csproj" --configuration Release
